#define INT 0
#define CHAR 1
#define RETURN 2
#define FUNC 3
#define WHILE 4
#define IF 5
#define THEN 6
#define ELSE 7
#define L_Brace 8
#define R_Brace 9
#define L_Paren 10
#define R_Paren 11
#define equal 12
#define colon 13
#define quality 14
#define same 15
#define add 16
#define mul 17
#define WORD 18
#define NUM 19
#define comma 20

